# Generated by Django 2.2.3 on 2019-07-20 20:55
import random
from django.db import migrations
from faker import Faker

def insert_common_employees(apps, schema_editor):
    fake = Faker()
    Employee = apps.get_model('employee', 'Employee')
    departments = ['Architeture', 'E-commerce', 'Mobile']
    for i in range(3):
        employee = Employee(name= fake.name(), email= fake.email(), department= random.choice(departments))
        employee.save()

class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_common_employees) 
    ]
